package main

import (
	"FenixOnPremDemoTestInstructionAdmin/TestInstructionsAndTesInstructionContainersAndAllowedUsers"
	"fmt"
)

func main() {

	TestInstructionsAndTesInstructionContainersAndAllowedUsers.GenerateTestInstructions_OnPremDemo()

	fmt.Println(TestInstructionsAndTesInstructionContainersAndAllowedUsers.TestInstructionsAndTestInstructionContainersAndAllowedUsers_OnPremDemo)
}
